cart/urls.py
from django.urls import path
from cart.views import cart_add,cart_detail,cart_remove

app_name = "cart"

urlpatterns = [
    path("",cart_detail,name='cart_detail'),
    path("add/<int:product_id>",cart_add,name='cart_add'),
    path("remove/<int:product_id>/",cart_remove,name="cart_remove"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path("",include("vendors.urls")),
    path("cart/",include('cart.urls',namespace='cart')),
    path("orders/",include('orders.urls',namespace='orders')),
    path("profiles/",include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from profiles.views import ProfileDetailView,ProfileUpdateView

app_name = 'profiles'


urlpatterns= [
    # path('create/',ProfileCreateView.as_view(),name="profile_create"),
    path('<int:pk>/update/',ProfileUpdateView.as_view(),name="profile_update"),
    path("<int:pk>/detail/",ProfileDetailView.as_view(),name='profile_detail'),
]

vendors/urls.py
from django.urls import path
from vendors.views import (ProductCreateView, ServiceCreateView, ProductServiceListView,
                           ProductDetailView,ServiceDetailView,ProductUpdateView,ServiceUpdateView,
                           ProductDeleteView,ServiceDeleteView,UserProductServiceListView,
                           get_products,get_services,product_servict_list)


urlpatterns = [
    path("create_product/",ProductCreateView.as_view(),name="create_product"),
    path("create_service/",ServiceCreateView.as_view(),name='create_service'),
    path("product/<int:pk>/",ProductDetailView.as_view(),name="product_detail"),
    path("service/<int:pk>/",ServiceDetailView.as_view(),name="service_detail"),
    path("product/<int:pk>/edit/",ProductUpdateView.as_view(),name="edit_product"),
    path("service/<int:pk>/edit/",ServiceUpdateView.as_view(),name="edit_service"),
    path("product/<int:pk>/delete/",ProductDeleteView.as_view(),name="delete_product"),
    path("service/<int:pk>/delete/",ServiceDeleteView.as_view(),name="delete_service"),
    path("user-product-service-list/",UserProductServiceListView.as_view(),
         name='user_product_service_list'),
    path('get_products/<int:offset>/',get_products,name='get_products'),
    path('get_services/<int:offset>/',get_services,name='get_services'),
    path("",product_servict_list,name="home"),



]

vendors/models.py
from django.db import models
from accounts.models import CustomUser,CustomPermission

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
    def __lt__(self, other):
        if isinstance(other, ProductCategory):
            return self.name < other.name
        return NotImplemented
    
class ServiceCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name



class CommonFields(models.Model):
    vendor = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    item_name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='product_images/',null=True,blank=True)

    class Meta:
        abstract = True

class Product(CommonFields):
    category = models.ForeignKey(ProductCategory,on_delete=models.CASCADE)
    items_in_store = models.IntegerField(null=True,blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.item_name

class Service(CommonFields):
    category = models.ForeignKey(ServiceCategory,on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    pricing_type = models.CharField(max_length=20,choices=[
        ('hourly','Hourly'),
        ('daily','Daily'),
        ('per_job','Job'),
    ])
    hourly_rate = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True)
    daily_rate = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True)
    per_job_rate = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True)

    def __str__(self):
        return self.item_name

vendors/forms.py
# forms.py

from django import forms
from .models import Product, Service

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['item_name', 'description', 'image', 'category', 'items_in_store', 'price']

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['item_name', 'description', 'image', 'category', 'is_active', 'pricing_type', 'hourly_rate', 'daily_rate', 'per_job_rate']

vendors/views.py
from typing import Any
import pandas as pd

from django import http
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse,JsonResponse
from django.shortcuts import render
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView,DetailView
from django.http import Http404
from django.db.models import Q

from rest_framework.response import Response
from rest_framework.decorators import api_view

from cart.forms import CartAddProductForm
from orders.models import Order,OrderItem
from vendors.dataProcess import data_process







from vendors.models import Product,Service
from vendors.forms import ProductForm, ServiceForm
from vendors.serializers import ProductsSerializer,ServiceSerializer

# Create your views here.

class ProductCreateView(LoginRequiredMixin,CreateView):
    model = Product
    form_class = ProductForm
    template_name = "vendors/create_product.html"
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.vendor = self.request.user

        if 'save_and_add_new' in self.request.POST:
            #save and add new logic here
            self.success_url = reverse_lazy("create_product")
        elif 'save' in self.request.POST:
            #Save logic here
            self.success_url = reverse_lazy("home")

        return super().form_valid(form)

class ServiceCreateView(LoginRequiredMixin,CreateView):
    model = Service
    form_class = ServiceForm
    template_name = "vendors/create_service.html"
    success_url = reverse_lazy("home")

    def form_valid(self, form):
        form.instance.vendor = self.request.user
        return super().form_valid(form)




class ProductServiceListView(ListView):
    model = Product
    # template_name = "product_service_list.html"
    template_name = "vendors/p_and_s.html"
    context_object_name = "product_service_list"

    def get_queryset(self):
        return Product.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['service_list'] = Service.objects.all()
        return context
    

class ProductDetailView(DetailView):
    model = Product
    template_name = "vendors/product_detail.html"
    context_object_name = "product"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_form'] = CartAddProductForm()
        return context
    
    
class ServiceDetailView(DetailView):
    model = Service
    template_name = "vendors/service_detail.html"
    context_object_name = "service"


class VendorRequiredMixin(LoginRequiredMixin):
    """
    Mixin to ensure that the logged-in user is the vendor
    """

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().vendor != self.request.user:
            raise Http404("You do not have permission to edit this")
        return super().dispatch(request,*args,**kwargs)
    

class ProductUpdateView(VendorRequiredMixin,UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "vendors/edit_product.html"
    success_url = reverse_lazy("home")

class ServiceUpdateView(VendorRequiredMixin,UpdateView):
    model = Service
    form_class = ServiceForm
    template_name = "vendors/edit_service.html"
    success_url = reverse_lazy('home')


class ProductDeleteView(VendorRequiredMixin,DeleteView):
    model = Product
    context_object_name = "product"
    template_name = "vendors/delete_product.html"
    success_url = reverse_lazy("home")

class ServiceDeleteView(VendorRequiredMixin,DeleteView):
    model = Service
    context_object_name = "service"
    template_name = "vendors/delete_service.html"
    success_url = reverse_lazy("home")

class UserProductServiceListView(LoginRequiredMixin,ListView):
    template_name = "vendors/user_product_service_list.html"
    context_object_name = "user_product_service_list"

    def get_queryset(self):
        user = self.request.user
        product_queryset = Product.objects.filter(vendor=user)
        service_queryset = Service.objects.filter(vendor = user)

        #All the orderItem related to the vendor
        orderItem_queryset = OrderItem.objects.filter(product__vendor=user)
        data = []
        for idx,order_item in enumerate(orderItem_queryset,start=1):
            data.append({
                'sn':idx,
                "Order id":order_item.order.id,
                "Date":order_item.order.created,
                "Product":order_item.product.item_name,
                "Category":order_item.product.category.name,
                "Items Sold":order_item.quantity,
                "Price":order_item.price,
            })
        df = pd.DataFrame(data)
        df['Date'] = df['Date'].dt.date
        # print(df)
        chart_data_json,line_chart_data_json,line_chart_data_price_json, pie_chart_data_price_json,product_list,chart_data_product,forecasts = data_process(df)
        print(forecasts)
        all_my_products = []
        for product in product_queryset:
            product_sell = {}
           
            product_sold = 0
            pending_orders = 0
            for order in orderItem_queryset:
                if(order.product == product):
                    if(order.order.paid):
                        product_sold += order.quantity
                    else:
                        pending_orders += order.quantity
            product_sell["product"] = product
            product_sell["total_sold"] = product_sold
            product_sell["PendingOrders"] = pending_orders
            product_sell["Earning"] = product_sold*product.price
            product_sell['In Store'] = product.items_in_store
            # print(product_sell)
            all_my_products.append(product_sell)
       
        total_earning = sum(item['Earning'] for item in all_my_products)

        return {'products':product_queryset,'services':service_queryset,'orderitems':orderItem_queryset,
                'allProducts':all_my_products,"totalEarning":total_earning,
                "chart_data":chart_data_json,
                "line_chart_data":line_chart_data_json,
                "line_chart_price_data":line_chart_data_price_json,
                "pie_chart_price_data":pie_chart_data_price_json,
                "product_list":product_list,
                "chart_data_product":chart_data_product,
                "forecasts":forecasts}
    


def get_products(request,offset):
    products = Product.objects.all()[offset:offset +12]
    data = [{'name':product.item_name,'image':product.image.url,
             'vendor':product.vendor.username}
             for product in products]
    return JsonResponse({'data':data})


def get_services(request,offset):
    services = Service.objects.all()[offset:offset +12]
    data = [{'name':service.item_name,'image':service.image.url,
             'vendor':str(service.vendor.username)} for service in services]
    return JsonResponse({'data':data})





# def index(request):
#     return render(request,'index.html')

def product_servict_list(request,category='products'):
    
    category = request.GET.get('category','products')
    print(category)

    products = Product.objects.all()
    services = Service.objects.all()

    #handle search logic
    search_query = request.GET.get('search',"")
    if search_query:
        search_filter = (
            Q(item_name__icontains =search_query)|
            Q(vendor__username__icontains = search_query)|
            Q(category__name__icontains = search_query)
        )
        products = products.filter(search_filter)
        services = services.filter(search_filter)

    #Handle price range filtering 
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')

    if min_price:
        products = products.filter(price__gte=min_price)
        # services = services.filter(service_fee_gte=min_price)
    if max_price:
        products = products.filter(price__lte=max_price)
        # services = services.filter(service_fee__lte=max_price)

        
    
    return render(request,'vendors/index.html',
                  {'products':products,
                   'services':services,
                   'category':category})

vendors/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <h1>Product List</h1>

    <div class="row">
        <div class="col-md-3">
            <form method="get" action="{% url 'home'%}" class="mb-4">
                <div class="form-group">
                    <label for="search">Search:</label>
                    <input type="text" id="search" name="search" class="form-control">

                </div>

                <div class="from-group">
                    <label for="min_price">Min Price: </label>
                    <input type="number" id="min_price" name="min_price" step="0.01" class="form-control">

                </div>

                <div class="form-group">
                    <label for="max_price">Max Price:</label>
                    <input type="number" id="max_price" name="max_price" step="0.01" class="form-control">
                </div>

                <button type="submit" class="btn btn-primary">Filter</button>
                <input type="hidden" name="category" id="category_input" value="{{ category }}">



            </form>

            <button onclick="toggleCategory()" id="toggleButton" class="btn btn-secondary">
                Switch to Services
            </button>
        </div>

        <div class="col-md-9" id="product_list" {% if category == 'services' %} style="display: none;" {% endif %}>
            <div class="row">
                {% for product in products %}
                {% if forloop.counter0|divisibleby:3 %}
                    </div><div class="row">
                {% endif %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top" alt="{{product.item_name}}">
                        {% else %}
                        <img src="{% static 'images/no_image.png' %}">
                        

                        {% endif %}

                        <div class="card-body">
                            <h5 class="card-title">{{ product.item_name }}</h5>
                            <p class="card-text">
                                
                                <a class="nav-link" href="{% url 'profiles:profile_detail' product.vendor.profile.id%}">
                                    Vendor: {{product.vendor}}
                                </a>
                            </p>
                            <p class="card-text">Price: ${{ product.price }}</p>
                            <a href="{% url 'product_detail' product.id %}" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

            </div>
            
        </div>

        <div class="col-md-9" id="service_list" {% if category == 'products' %} style="display: none;" {% endif %}>
            <div class="row">
                {% for service in services %}
                {% if forloop.counter0|divisibleby:3 %}
                    </div><div class="row">
                {% endif %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        {% if service.image %}
                        <img src="{{ service.image.url }}" class="card-img-top" alt="{{service.item_name}}">
                        {% else %}
                        <img src="{% static 'images/no_image.png' %}">
                        

                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ service.item_name }}</h5>
                            <p class="card-text">Vendor: {{ service.vendor }}</p>
                            
                            <a href="{% url 'service_detail' service.id %}" class="btn btn-primary">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

            </div>
            
        </div>

        



    </div>
</div>


<script>
    function toggleCategory(){
        console.log("Button clicked");
        const toggleButton = document.getElementById('toggleButton');
        console.log(toggleButton.innerText)
        var productList = document.getElementById('product_list');
        var serviceList = document.getElementById('service_list');
        var categoryInput = document.getElementById('category_input');


        if (productList.style.display === 'none'){
            productList.style.display = 'block';
            serviceList.style.display = 'none';
            toggleButton.innerText = 'Switch to Services';
            categoryInput.value = 'products';

        } else {
            productList.style.display = 'none';
            serviceList.style.display = 'block';
            toggleButton.innerText = 'Switch to Products';
            categoryInput.value = 'services';
        }
    }
</script>



{% endblock %}

vendors/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container my-4">
        <h2 class="mb-3">{{ product.item_name }}</h2>
        <p class="mb-3">Description: {{ product.description }}</p>
        
        {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.item_name }} Image" class="img-fluid mb-3">
        {% else %}
            <img src="{% static 'images/default_image.jpg' %}" alt="Default image" class="img-fluid mb-3">
        {% endif %}
        
        <p class="mb-3">Price: {{ product.price }}</p>
        <h5 class="mb-3"><a class="nav-link" href="{% url 'profiles:profile_detail' product.vendor.profile.id%}">Vendor: {{product.vendor}}</a></h5>
        
        {% if product.vendor == request.user %}
            <div class="mb-3">
                <a href="{% url 'edit_product' pk=product.pk %}" class="btn btn-outline-primary mr-2">Edit</a>
                <a href="{% url 'delete_product' pk=product.pk %}" class="btn btn-outline-danger">Delete</a>
            </div>
        {% endif %}

        <form method="post" action="{% url 'cart:cart_add' product.id %}" class="mb-3">
            {% csrf_token %}
            {{ cart_form.as_p }}
            <button type="submit" class="btn btn-success">Add to Cart</button>
        </form>
    </div>
{% endblock %}