cart/urls.py
from django.urls import path
from cart.views import cart_add,cart_detail,cart_remove

app_name = "cart"

urlpatterns = [
    path("",cart_detail,name='cart_detail'),
    path("add/<int:product_id>",cart_add,name='cart_add'),
    path("remove/<int:product_id>/",cart_remove,name="cart_remove"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path("",include("vendors.urls")),
    path("cart/",include('cart.urls',namespace='cart')),
    path("orders/",include('orders.urls',namespace='orders')),
    path("profiles/",include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from orders.views import order_create_view,OrderPDFView

app_name = "orders"

urlpatterns = [
    path('create/',order_create_view,name="order_create"),
    path('order/<int:pk>/pdf/',OrderPDFView.as_view(),name="order_pdf"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from typing import Any
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError



class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField()
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

  
    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        product = self.product

        if quantity > product.items_in_store:
            raise ValidationError(f"Only {product.items_in_store} items available")
        return quantity

cart/views.py
from django.shortcuts import render,redirect,get_list_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages

from vendors.models import Product

from cart.cart import Cart
from cart.forms import CartAddProductForm


# Create your views here.
@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_list_or_404(Product,id=product_id)
    product = product[0]
    form = CartAddProductForm(request.POST)
    form.product = product #set the product attribute 

    print("*******************")
    print(product)
   

    if form.is_valid():
        cd = form.cleaned_data
        print(product.items_in_store)
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
        return redirect('cart:cart_detail')
    return render(request,'vendors/product_detail.html',{'product':product,'cart_form':form})
        
    
@require_POST 
def cart_remove(request,product_id):
    print("**************************")
    print(f"Removing {product_id}")
    cart = Cart(request)
    product =get_list_or_404(Product,id=product_id)
    print(product[0])
    cart.remove(product[0])
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['form'] = CartAddProductForm(initial={
            'quantity':item['quantity'],
            'override':True
        })
        # print(item['form'])
    return render(request,'cart/detail.html',{'cart':cart})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <h1>
        Your shopping cart
    </h1>
    
    <table class="table">
        <thead>
            <tr>
                <th>
                    Image
                </th>
                <th>
                    Product
                </th>
    
                <th>
                    Quantity
                </th>
    
                <th>
                    Remove
                </th>
                <th>
                    Unit Price
                </th>
    
                <th>
                    Price
                </th>
            </tr>
        </thead>
    
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{product.get_absolute_url }}">
                            {% if product.image %}
                            
                            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-thumbnail" style="max-height: 50px; max-width: 50px;">
                            {% else %}
                            {% static "img/no_image.png" %}
                            {% endif %}
    
    
                        </a>
                    </td>
                    <td>
                        {{product.item_name}}
                    </td>
    
                    <td>
                      
                        <form action="{% url 'cart:cart_add' product.id %}" method="post" class="form-inline">
                            {{ item.form.quantity }}
                            {{ item.form.override }}
                            
                           
                            <input type="submit" value="Update" class="btn btn-primary btn-sm ml-2">
                            {% csrf_token %}
                        </form>
                        
                    </td>
    
                    <td>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                            <input type="submit" value="Remove" class="btn btn-danger btn-sm">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        ${{item.price}}
                    </td>
    
                    <td>
                        ${{ item.total_price }}
                    </td>
                </tr>
    
            {% endwith %}
    
            {% endfor %}
    
            <tr>
                <td>Total</td>
                <td colspan="4"></td>
                <td>
                    ${{cart.get_total_price}}
                </td>
            </tr>
        </tbody>
    </table>
    
    <p>
        <a href="{% url 'home' %}" class="btn btn-secondary">
            Continue Shopping
        </a>
    
        <a href="{% url 'orders:order_create' %}"class="btn btn-primary">
            Checkout
        </a>
    </p>
    

</div>


{% endblock %}