cart/urls.py
from django.urls import path
from cart.views import cart_add,cart_detail,cart_remove

app_name = "cart"

urlpatterns = [
    path("",cart_detail,name='cart_detail'),
    path("add/<int:product_id>",cart_add,name='cart_add'),
    path("remove/<int:product_id>/",cart_remove,name="cart_remove"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path("",include("vendors.urls")),
    path("cart/",include('cart.urls',namespace='cart')),
    path("orders/",include('orders.urls',namespace='orders')),
    path("profiles/",include('profiles.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from profiles.views import ProfileDetailView,ProfileUpdateView

app_name = 'profiles'


urlpatterns= [
    # path('create/',ProfileCreateView.as_view(),name="profile_create"),
    path('<int:pk>/update/',ProfileUpdateView.as_view(),name="profile_update"),
    path("<int:pk>/detail/",ProfileDetailView.as_view(),name='profile_detail'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.models import CustomUser

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_pic/',blank=True,null=True)
    first_name = models.CharField(max_length=50,blank=True) 
    last_name = models.CharField(max_length=50,blank=True)
    email = models.EmailField(blank=True)
    address = models.CharField(max_length=250,blank=True)
    postal_code= models.CharField(max_length=20,blank=True)
    city = models.CharField(max_length=20,blank=True)


    def __str__(self):
        return self.user.username

profiles/forms.py
from django import forms
from profiles.models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name','last_name','email',
                  'address','postal_code','city','image']

profiles/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.views.generic import CreateView,UpdateView,DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404

from profiles.models import Profile
from profiles.forms import ProfileForm


# Create your views here.
# class ProfileCreateView(LoginRequiredMixin,CreateView):
#     model = Profile
#     form_class = ProfileForm
#     template_name = 'profile_form.html'
#     success_url = reverse_lazy('profile_detail')

#     def form_valid(self,form):
#         form.instance.user = self.request.user
#         return super().form_valid(form)
    
class ProfileUpdateView(LoginRequiredMixin,UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = "profile_form.html"
    

    def get_object(self,queryset=None):
        return self.model.objects.get(user=self.request.user)
    
    def get_success_url(self):
        return reverse_lazy("profiles:profile_detail",kwargs={'pk':self.request.user.profile.pk})

class ProfileDetailView(DetailView):
    model = Profile
    template_name = "profile_detail.html"

    def get_object(self,queryset=None):
        profile_id = self.kwargs.get('pk')
        return get_object_or_404(self.model,pk=profile_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = context['object']
        return context
    
    
    
    

profiles/templates/profile_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="container">
        <h2>{{ profile.first_name }}'s Profile</h2>
        
        <div class="row">
            <div class="col-md-4">
                {% if profile.image %}
                    <img src="{{ profile.image.url }}" alt="{{ user.username }}'s Profile Image" class="img-fluid rounded-circle">
                {% else %}
                    
                    <img src="{% static 'img/no_image.png' %}" alt="Default Profile Image" class="img-fluid rounded-circle">
                    {% endif %}
            </div>
            
            <div class="col-md-8">
                <p>First Name: {{ profile.first_name }}</p>
                <p>Last Name: {{ profile.last_name }}</p>
                <p>Email: {{ profile.email }}</p>
                <p>Address: {{ profile.address }}</p>
                <p>Postal Code: {{ profile.postal_code }}</p>
                <p>City: {{ profile.city }}</p>
                {% if request.user == profile.user %}
                <a href="{% url 'profiles:profile_update' user.profile.pk %}">Update Profile</a>
                {% endif %}
            </div>
        </div>

    </div>

{% endblock %}

profiles/templates/profile_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>Profile form</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">
            Save
        </button>
    </form>

{% endblock %}